# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Concert <- function(X, y, n_vec, tau, q_k, eta, q_0, threshold = 1e-6, max_iter = 1000L) {
    .Call(`_CONCERT_Concert`, X, y, n_vec, tau, q_k, eta, q_0, threshold, max_iter)
}

